// Dev-only generator for public/data/capitals.json.
// Keyed by the EXACT country name in public/data/flags.json so the Capitals
// bonus mode can join against the flag emoji + region tags. Entries are emitted
// in flags.json order. Countries/territories with no conventional capital
// (Antarctica, Hong Kong, Macau, Tokelau) are intentionally omitted; the quiz
// also skips self-named capitals (Singapore, Monaco, Vatican City, Gibraltar)
// where the capital equals the country name.
const fs = require('fs');
const path = require('path');

const CAPITALS = {
    'Afghanistan': 'Kabul',
    'Åland Islands': 'Mariehamn',
    'Albania': 'Tirana',
    'Algeria': 'Algiers',
    'American Samoa': 'Pago Pago',
    'Andorra': 'Andorra la Vella',
    'Angola': 'Luanda',
    'Anguilla': 'The Valley',
    // Antarctica — no capital (omitted)
    'Antigua and Barbuda': "Saint John's",
    'Argentina': 'Buenos Aires',
    'Armenia': 'Yerevan',
    'Aruba': 'Oranjestad',
    'Ascension Island': 'Georgetown',
    'Australia': 'Canberra',
    'Austria': 'Vienna',
    'Azerbaijan': 'Baku',
    'Bahamas': 'Nassau',
    'Bahrain': 'Manama',
    'Bangladesh': 'Dhaka',
    'Barbados': 'Bridgetown',
    'Basque Country': 'Vitoria-Gasteiz',
    'Belarus': 'Minsk',
    'Belgium': 'Brussels',
    'Belize': 'Belmopan',
    'Benin': 'Porto-Novo',
    'Bermuda': 'Hamilton',
    'Bhutan': 'Thimphu',
    'Bolivia': 'Sucre',
    'Bosnia and Herzegovina': 'Sarajevo',
    'Botswana': 'Gaborone',
    'Brazil': 'Brasília',
    'British Virgin Islands': 'Road Town',
    'Brunei': 'Bandar Seri Begawan',
    'Bulgaria': 'Sofia',
    'Burkina Faso': 'Ouagadougou',
    'Burundi': 'Gitega',
    'Cambodia': 'Phnom Penh',
    'Cameroon': 'Yaoundé',
    'Canada': 'Ottawa',
    'Canary Islands': 'Las Palmas de Gran Canaria',
    'Cape Verde': 'Praia',
    'Catalonia': 'Barcelona',
    'Cayman Islands': 'George Town',
    'Central African Republic': 'Bangui',
    'Chad': "N'Djamena",
    'Chile': 'Santiago',
    'China': 'Beijing',
    'Christmas Island': 'Flying Fish Cove',
    'Cocos (Keeling) Islands': 'West Island',
    'Colombia': 'Bogotá',
    'Comoros': 'Moroni',
    'Cook Islands': 'Avarua',
    'Costa Rica': 'San José',
    'Croatia': 'Zagreb',
    'Cuba': 'Havana',
    'Curaçao': 'Willemstad',
    'Cyprus': 'Nicosia',
    'Czech Republic': 'Prague',
    'Democratic Republic of the Congo': 'Kinshasa',
    'Denmark': 'Copenhagen',
    'Djibouti': 'Djibouti City',
    'Dominica': 'Roseau',
    'Dominican Republic': 'Santo Domingo',
    'Ecuador': 'Quito',
    'Egypt': 'Cairo',
    'El Salvador': 'San Salvador',
    'England': 'London',
    'Equatorial Guinea': 'Malabo',
    'Eritrea': 'Asmara',
    'Estonia': 'Tallinn',
    'Eswatini': 'Mbabane',
    'Ethiopia': 'Addis Ababa',
    'Falkland Islands': 'Stanley',
    'Faroe Islands': 'Tórshavn',
    'Fiji': 'Suva',
    'Finland': 'Helsinki',
    'France': 'Paris',
    'French Polynesia': 'Papeete',
    'Gabon': 'Libreville',
    'Galicia': 'Santiago de Compostela',
    'Gambia': 'Banjul',
    'Georgia': 'Tbilisi',
    'Germany': 'Berlin',
    'Ghana': 'Accra',
    'Gibraltar': 'Gibraltar',
    'Greece': 'Athens',
    'Greenland': 'Nuuk',
    'Grenada': "Saint George's",
    'Guam': 'Hagåtña',
    'Guatemala': 'Guatemala City',
    'Guernsey': 'Saint Peter Port',
    'Guinea': 'Conakry',
    'Guinea-Bissau': 'Bissau',
    'Guyana': 'Georgetown',
    'Haiti': 'Port-au-Prince',
    'Honduras': 'Tegucigalpa',
    // Hong Kong — special administrative region, no capital (omitted)
    'Hungary': 'Budapest',
    'Iceland': 'Reykjavík',
    'India': 'New Delhi',
    'Indonesia': 'Jakarta',
    'Iran': 'Tehran',
    'Iraq': 'Baghdad',
    'Ireland': 'Dublin',
    'Isle of Man': 'Douglas',
    'Israel': 'Jerusalem',
    'Italy': 'Rome',
    'Ivory Coast': 'Yamoussoukro',
    'Jamaica': 'Kingston',
    'Japan': 'Tokyo',
    'Jersey': 'Saint Helier',
    'Jordan': 'Amman',
    'Kazakhstan': 'Astana',
    'Kenya': 'Nairobi',
    'Kiribati': 'Tarawa',
    'Kosovo': 'Pristina',
    'Kuwait': 'Kuwait City',
    'Kyrgyzstan': 'Bishkek',
    'Laos': 'Vientiane',
    'Latvia': 'Riga',
    'Lebanon': 'Beirut',
    'Lesotho': 'Maseru',
    'Liberia': 'Monrovia',
    'Libya': 'Tripoli',
    'Liechtenstein': 'Vaduz',
    'Lithuania': 'Vilnius',
    'Luxembourg': 'Luxembourg City',
    // Macau — special administrative region, no capital (omitted)
    'Madagascar': 'Antananarivo',
    'Malawi': 'Lilongwe',
    'Malaysia': 'Kuala Lumpur',
    'Maldives': 'Malé',
    'Mali': 'Bamako',
    'Malta': 'Valletta',
    'Marshall Islands': 'Majuro',
    'Martinique': 'Fort-de-France',
    'Mauritania': 'Nouakchott',
    'Mauritius': 'Port Louis',
    'Mexico': 'Mexico City',
    'Micronesia': 'Palikir',
    'Moldova': 'Chișinău',
    'Monaco': 'Monaco',
    'Mongolia': 'Ulaanbaatar',
    'Montenegro': 'Podgorica',
    'Montserrat': 'Brades',
    'Morocco': 'Rabat',
    'Mozambique': 'Maputo',
    'Myanmar': 'Naypyidaw',
    'Namibia': 'Windhoek',
    'Nauru': 'Yaren',
    'Nepal': 'Kathmandu',
    'Netherlands': 'Amsterdam',
    'New Caledonia': 'Nouméa',
    'New Zealand': 'Wellington',
    'Nicaragua': 'Managua',
    'Niger': 'Niamey',
    'Nigeria': 'Abuja',
    'Niue': 'Alofi',
    'Norfolk Island': 'Kingston',
    'North Korea': 'Pyongyang',
    'North Macedonia': 'Skopje',
    'Northern Ireland': 'Belfast',
    'Northern Mariana Islands': 'Saipan',
    'Norway': 'Oslo',
    'Oman': 'Muscat',
    'Pakistan': 'Islamabad',
    'Palau': 'Ngerulmud',
    'Palestine': 'Ramallah',
    'Panama': 'Panama City',
    'Papua New Guinea': 'Port Moresby',
    'Paraguay': 'Asunción',
    'Peru': 'Lima',
    'Philippines': 'Manila',
    'Pitcairn Islands': 'Adamstown',
    'Poland': 'Warsaw',
    'Portugal': 'Lisbon',
    'Puerto Rico': 'San Juan',
    'Qatar': 'Doha',
    'Republic of the Congo': 'Brazzaville',
    'Romania': 'Bucharest',
    'Russia': 'Moscow',
    'Rwanda': 'Kigali',
    'Saint Helena': 'Jamestown',
    'Saint Kitts and Nevis': 'Basseterre',
    'Saint Lucia': 'Castries',
    'Saint Vincent and the Grenadines': 'Kingstown',
    'Samoa': 'Apia',
    'San Marino': 'City of San Marino',
    'Sao Tome and Principe': 'São Tomé',
    'Saudi Arabia': 'Riyadh',
    'Scotland': 'Edinburgh',
    'Senegal': 'Dakar',
    'Serbia': 'Belgrade',
    'Seychelles': 'Victoria',
    'Sierra Leone': 'Freetown',
    'Singapore': 'Singapore',
    'Sint Maarten': 'Philipsburg',
    'Slovakia': 'Bratislava',
    'Slovenia': 'Ljubljana',
    'Solomon Islands': 'Honiara',
    'Somalia': 'Mogadishu',
    'South Africa': 'Pretoria',
    'South Korea': 'Seoul',
    'South Sudan': 'Juba',
    'Spain': 'Madrid',
    'Sri Lanka': 'Sri Jayawardenepura Kotte',
    'Sudan': 'Khartoum',
    'Suriname': 'Paramaribo',
    'Sweden': 'Stockholm',
    'Switzerland': 'Bern',
    'Syria': 'Damascus',
    'Taiwan': 'Taipei',
    'Tajikistan': 'Dushanbe',
    'Tanzania': 'Dodoma',
    'Thailand': 'Bangkok',
    'Timor-Leste': 'Dili',
    'Togo': 'Lomé',
    // Tokelau — no capital; each atoll self-administers (omitted)
    'Tonga': "Nuku'alofa",
    'Trinidad and Tobago': 'Port of Spain',
    'Tristan da Cunha': 'Edinburgh of the Seven Seas',
    'Tunisia': 'Tunis',
    'Turkey': 'Ankara',
    'Turkmenistan': 'Ashgabat',
    'Turks and Caicos Islands': 'Cockburn Town',
    'Tuvalu': 'Funafuti',
    'Uganda': 'Kampala',
    'Ukraine': 'Kyiv',
    'United Arab Emirates': 'Abu Dhabi',
    'United Kingdom': 'London',
    'United States': 'Washington, D.C.',
    'United States Virgin Islands': 'Charlotte Amalie',
    'Uruguay': 'Montevideo',
    'Uzbekistan': 'Tashkent',
    'Vanuatu': 'Port Vila',
    'Vatican City': 'Vatican City',
    'Venezuela': 'Caracas',
    'Vietnam': 'Hanoi',
    'Wales': 'Cardiff',
    'Western Sahara': 'El Aaiún',
    'Yemen': "Sana'a",
    'Zambia': 'Lusaka',
    'Zimbabwe': 'Harare',
};

const flagsPath = path.join(__dirname, '..', 'public', 'data', 'flags.json');
const outPath = path.join(__dirname, '..', 'public', 'data', 'capitals.json');
const flags = JSON.parse(fs.readFileSync(flagsPath, 'utf8'));

// Countries/territories with no conventional capital — these are intentionally
// absent from CAPITALS and must NOT be reported as missing.
const NO_CAPITAL = new Set(['Antarctica', 'Hong Kong', 'Macau', 'Tokelau']);

const missing = [];
const out = [];
for (const f of flags) {
    if (NO_CAPITAL.has(f.country)) continue;
    const capital = CAPITALS[f.country];
    if (!capital) { missing.push(f.country); continue; }
    out.push({ country: f.country, capital });
}

// Sanity: catch any CAPITALS keys that don't match a flags.json country name.
const flagNames = new Set(flags.map((f) => f.country));
const orphans = Object.keys(CAPITALS).filter((c) => !flagNames.has(c));

if (missing.length) {
    console.error('MISSING capitals for:', missing.join(', '));
}
if (orphans.length) {
    console.error('ORPHAN keys (not in flags.json):', orphans.join(', '));
}

fs.writeFileSync(outPath, JSON.stringify(out, null, 2) + '\n');
console.log(`Wrote ${out.length} capitals to ${outPath}`);
console.log(`(flags total ${flags.length}, no-capital ${NO_CAPITAL.size}, missing ${missing.length}, orphans ${orphans.length})`);
